import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import SessionProvider from "./components/SessionProvider";
import Nav from './components/Nav';


const inter = Inter({ subsets: ['latin'] })

import { ThirdwebProvider } from "./components/ThirdwebProvider";
import {metamaskWallet}  from "./components/metamaskWallet";
import { ConnectWallet } from './components/ConnectWallet';
import ConnectAddress from './components/connectAddress';
import GraphQ from './components/GraphQ';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }) {

  const session = await getServerSession();


  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>{children}
      
        <ThirdwebProvider supportedWallets={[metamaskWallet]} activeChain="mumbai" clientId="ff8747ba0218ede20259d514affd5a17" >
          
            <Nav/>
            
            <ConnectWallet theme="dark"/>
            <ConnectAddress/>
            <GraphQ/>
        </ThirdwebProvider>
          
        </SessionProvider>  
      </body>
    </html>
  )
}
